---
title: "Resultat"
subtitle: ""
date: '2020-09-06'
output: html_document
weight: 30

---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(here)
library(gt)
library(kableExtra)
library(readxl)
```

Här är den aktuella poängställningen efter **de första 3** av de totalt 5 deltävlingarna:

```{r data_prep, include=FALSE}
# Create file path
files <- list.files(path = here("assets", "data"), pattern = "Result*", full.names = T)

# Import files into dataframe
res <- map_dfr(files, read_xlsx)
View(res)

## Calculate points per competition

# Add new variable "Points"
tot <- res %>% mutate(Points = case_when(
  Place == 1 ~ 25,
  Place == 2 ~ 22,
  Place == 3 ~ 19,
  Place == 4 ~ 17,
  Place == 5 ~ 15,
  Place == 6 ~ 13,
  Place == 7 ~ 12,
  Place == 8 ~ 11,
  Place == 9 ~ 10,
  Place == 10 ~ 9,
  Place == 11 ~ 8,
  Place == 12 ~ 7,
  Place == 13 ~ 6,
  Place == 14 ~ 5,
  Place == 15 ~ 4,
  Place == 16 ~ 3,
  Place == 17 ~ 2,
  TRUE ~ 1
))
View(tot)

##  Change format for output - create "pivot table" with points per competition
piv_comp <- tot %>% 
  select(Name, CompNo, Points) %>% 
  pivot_wider(names_from = CompNo, values_from = Points )
View(piv_comp)

## Calculate grand total points for all competitions (1-2)
grand_tot_1to3 <- tot %>% group_by(Name) %>%
  summarise(sum_points = sum(Points))
View(grand_tot_1to3)

# Create new piv df with totals column
res_1to3 <- piv_comp %>%
  full_join(grand_tot_1to3, by = "Name") %>% 
  arrange(desc(sum_points))
# View(res_1to2)

# Add ranking
res_1to3 <- res_1to3 %>% mutate(rank = min_rank(desc(sum_points)))

res_1to3 <- res_1to3 %>% relocate(rank, .before = Name)


# Rename columns for final table
df <- res_1to3 %>% rename("#" = "rank", "Namn" = "Name", "Summa Poäng" = "sum_points")

```



```{r result_table, echo=FALSE}

# Cod from the first competition
# result1 <- tot %>% 
#   select(Name, Points) %>% 
#   rename(Namn = Name, Poäng = Points)

# Create tabel output using kableExtra package
kable(df) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
  
```

