---
title: Avbrott i KM
author: Andrés Lagerlöf
date: '2020-11-03'
slug: avbrott-i-km
categories: []
tags:
  - '2020'
  - korrigering
subtitle: ''
summary: ''
authors: []
lastmod: '2020-11-03T18:26:17+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

KM-tävlandet avbryts på obestämd tid i enlighet med Folkhälsomyndighetens senaste rekommendationer.

Det är med blandade känslor som tävlingsledningen måste böja sig för Folkhälsomyndighetens nya direktiv och skjuta upp KM till dess att pandemiläget tillåter tävlande igen.

Blandade känslor kanske låter konstigt? Javisst! Som ni säkert har märkt har tävlingsledningens egen representation i tävlandet gått från dåligt till bedrövligt. Som bäst har densamme lyckats lura till sig en 5:e placering. Inte att undra på att tävlingsledningen tillhört en av de mest frekventa lobbygrupperna som uppvaktat Folkhälsomyndigheten för att  införa hårda restriktioner och därmed behålla KM-titeln några dagar till. Det finns tydliga indikationer på att enorma belopp har transfererats från KMs kassa till konton i skatteparadis för att sedan mirakulöst återfinnas på myndighetens interna personalfestkonton. Vi får säkert anledning att återkomma till den här smutsiga historien. Inga grävande journalister med självaktning kommer att kunna hålla sina journalistspadar borta från den här skandalen!

Det är naturligtvis tråkigt att alla de andra 30 fäktarna som har rent mjöl i påsen ska behöva drabbas av tävlingsledningens tillkortakommanden, men som vi ser det i dagsläget måste folkhälsan sättas i först rum. Låt därför vår gemensamma ilska mot tävlingsledningen vara den morot som får oss att fördubbla våra ansträngningar i alla dom träningsformer som fortfarande kan utföras så att vi, när möjligheten väl ges, kommer igen och vinner nästa KM-deltävling!

Ta hand om er så ses vi snart igen på pisten!
