---
title: Inför deltävling 2
author: Andrés Gomez
date: '2020-09-29'
slug: infor-deltavling-2
categories: []
tags:
  - '2020'
  - deltävling
  - preview
  - "1"
subtitle: ''
summary: ''
authors: []
lastmod: '2020-10-03T10:52:45+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


Snart är det dags igen! Vi minns alla hur Jonathan med lätta steg och ett brett leende gav sig iväg i höstnatten efter att ha utraderat allt motstånd i årets första deltävling. Lika mycket minns vi Grigoris andraplats och CHs näsplugg som sporrade honom till en imponerande 3e placering.

Men vad har vi att se fram emot till nästa runda? Här är ett urval som tävlingens pressavdelning har sammanställt:

### Vad kan vi lära av SAF-pokalen?
Som förberedelse för KMs 2a deltävling var SAF vänliga nog att arrangera SAF-pokalen. Eftersom Jonathan redan vunnit första deltävlingen på KM så hoppade han över SAF-pokalen, men av allt att döma kommer han att göra väl ifrån sig i KMs deltävling 2.

Grigori visade sin klass och lät ingen motståndare tro annat. Tittar vi på hur han brukar prestera på deltävling 2 så vet vi att han har siktet inställt på seger (han vann i alla fall motsvarande tävling förra året).

Den som glömt bort Tor bör tänka sig för igen. En 2a plats på SAF skvallrar om en brant stigande formkurva och vi vet ju att Tor ständigt är en segerkandidat att räkna med.

CH valde på ett slugt sätt kliva ur helgens tävling lite tidigare för att spara på krafterna till KM. Han blir säkert att räkna med. Kan han briljera med ytterligare 3e plats? Högst troligt tror många.

Förkylning tvingade Karsten att avstå från första deltävlingen, men i helgen visade han att han sannerligen kommer att blanda sig in i toppstriden.

Elvira visade också var skåpet ska stå, hon kommer säkert att fortsätta i samma anda på KM.

Janne gjorde också bra ifrån sig så även där något att se upp för. 

Och slutligen, våra yngre förmågor som exempelvis Ian och Hugo...det är bara en tidsfråga innan dom kommer att roffa åt sig åtskilliga poäng i tävlingen.

Kort sagt, fältet är öppet för en hård, spännande och framförallt rolig drabbning.

**Vi ses på torsdag!**
